### ISSUE TITLE
deprecation warning when running role

### ISSUE THREAD

**Issue by victorklos** [fgci-org/ansible-role-cuda#13]
Thanks for your work! Setting up a deep learning rig is so easy now... Minor issue though; using the role gives:

```
TASK [CSC-IT-Center-for-Science.cuda : check if cuda_gpu_name0 ( /dev/nvidia0 ) exists] ***
[DEPRECATION WARNING]: always_run is deprecated. Use check_mode = no instead..
This feature will be removed in version 2.4. Deprecation warnings can be disabled
by setting deprecation_warnings=False in ansible.cfg.
```

My ansible version is 2.2.0, the default on debian stable (and debian testing, at the time of writing).

**Comment by martbhell** [comment]
Hello and thanks @victorklos ! 
I think you need to use a newer version of this role.
Seems that in ansible galaxy the version hasn't been updated for a while, probably auto-update never worked and then we renamed our organization on github and now I can't do it manually either :) 
I've opened https://github.com/ansible/galaxy-issues/issues/278

For now, perhaps you could install it manually by pointing to github?

**Comment by martbhell** [comment]
OK I got this role updated in ansible galaxy. Installing it with ansible-galaxy and both "CSCfi.cuda" and "CSC-IT-Center-for-Science.cuda" fetches the currently latest role (v1.5.4).
