### ISSUE TITLE
load /dev/nvidia0 before slurm role runs

### ISSUE THREAD

**Issue by A1ve5** [fgci-org/ansible-role-cuda#2]
after reinstall ansible-pull fails because it can't find /dev/nvidia0. nvidia-smi seems to "load" it. 
Figure out a way to have /dev/nvidia0 available for slurm role

**Comment by martbhell** [comment]
OK. This is done and slurm now successfully starts on io's GPU node on reboots.
Thanks @dgtim for the commands.

Related I found a service called nvidia-persistenced.service - but enabling that and modifying its  service file to have --persistence-mode did not make /dev/nvidia\* devices appear.
