### ISSUE TITLE
Galaxy latest version is 1.5.4

### ISSUE THREAD

**Issue by uda** [fgci-org/ansible-role-cuda#24]
The latest release here is 1.6.3 from a a month ago

**Comment by martbhell** [comment]
I wonder if https://github.com/CSCfi/ansible-role-cuda/blob/master/.travis.yml adding a travis notification would fix this.. like in https://github.com/CSCfi/ansible-role-slurm/blob/master/.travis.yml

**Comment by lae** [comment]
The webhook notification is necessary for Galaxy to pull updated tags, yeah.
