### ISSUE TITLE
Improve score on ansible galaxy

### ISSUE THREAD

**Issue by martbhell** [fgci-org/ansible-role-cuda#26]
Turns out galaxy also has some points system where we now only have 2.5/5 :(

https://galaxy.ansible.com/cscfi/cuda

<pre>
Syntax Score:0.5
Warnings: 9
3E303: systemctl used in place of systemd module
5E601: Don't compare to literal True/False
1E305: Use shell only when shell functionality is required

Metadata Score:4.5
Warnings: 1
1E702: Use 'galaxy_tags' rather than 'categories'
</pre>

**Comment by VilleS1** [comment]
All fixed, maybe it is better now.

**Comment by VilleS1** [comment]
Well, almost all. Score is good enough for me now.

**Comment by martbhell** [comment]
Nice that those shell chroot commands aren't needed with the image creates anymore!

**Comment by VilleS1** [comment]
Hmm, hope not.

**Comment by VilleS1** [comment]
Some of the patches broke containers, reverted those.

**Comment by VilleS1** [comment]
Quality score now 3.5 / 5. I am not touching this one anymore. If somebody wants to further improve it feel free to reopen the issue.
