### ISSUE TITLE
Still problems with new CUDA repo key

### ISSUE THREAD

**Issue by jabl** [fgci-org/ansible-role-cuda#6]
Seems https://github.com/CSC-IT-Center-for-Science/ansible-role-cuda/commit/17f6bb1c4a950c87d857a9060e1a33b4a69e93dc isn't enough, 'yum update' still complains about the key. However, running 'yum clean all' followed by 'yum update' works, apparently the cleanup makes it fetch the new key.

**Comment by jabl** [comment]
Maybe http://docs.ansible.com/ansible/rpm_key_module.html is the solution?

**Comment by jabl** [comment]
Oh, I was too fast earlier: running 'yum clean all' didn't actually help. It downloaded the packages, but prompted for the key before actually starting the installation.

**Comment by martbhell** [comment]
Does yum-cron also prompt for the key after a manual yum clean?

**Comment by jabl** [comment]
Sorry, lets forget about the yum clean. It's not relevant, I was just drawing conclusions too soon.

yum-cron doesn't install the updates. In /etc/yum/yum-cron.conf there is:

<pre>
# Uncomment to auto-import new gpg keys (dangerous)
# assumeyes = True
</pre>

so there is a way to make it accept the key, but, yeah, a bit dangerous to have yum-cron accept any random key. Better to use the rpm_key_module, I think.

(The strange thing I'm wondering about is why we haven't bumped into this issue earlier)

**Comment by martbhell** [comment]
Updated fgci-ansible with an updated cuda role that installs rpm-keys. Better now?

**Comment by jabl** [comment]
Yes, seems to work now based on testing manually, thanks! Lets wait until tomorrow if our GPU nodes have autoupdated by then as they should have.

**Comment by jabl** [comment]
Yup, seems to work now. Thanks!
